services:
  - type: web
    name: qams-web
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /
    autoDeploy: true
    # Por defecto escucha en el puerto 80 del contenedor si se especifica en el Dockerfile
    dockerContext: .
    dockerfilePath: ./Dockerfile
