import re

CHAPTER_1_CONTENT = """
    # =========================================================================
    # CAPÍTULO 1: MARCO REFERENCIAL
    # =========================================================================
    add_h1("Capítulo 1.- MARCO REFERENCIAL")

    add_h2("1.1 Introducción")
    add_p("En el paradigma de la ingeniería de software contemporánea, la calidad del software ha transitado de ser una fase aislada y tardía en el ciclo de desarrollo a consolidarse como el pilar estratégico fundamental que sostiene la viabilidad técnica, operativa, comercial y reputacional de cualquier producto o ecosistema digital moderno. La acelerada digitalización de la economía global, el surgimiento de arquitecturas distribuidas complejas, y la hiper-conectividad han provocado que los defectos de software no detectados tempranamente generen consecuencias catastróficas. Según investigaciones exhaustivas, como las derivadas del IBM Systems Sciences Institute y confirmadas por reportes recientes del Consortium for Information & Software Quality (CISQ), el costo de un defecto de software sigue un patrón de crecimiento exponencial: un defecto corregido durante la fase de diseño o conceptualización cuesta una fracción mínima en comparación a si es detectado durante la fase de pruebas (15 veces más) y alcanza un costo astronómico si dicho defecto se filtra al entorno de producción (hasta 100 veces más caro). Este costo en producción no solo incluye el esfuerzo técnico de refactorización (debugging, pruebas de regresión, despliegues de hotfixes), sino también los costos de oportunidad, penalizaciones por incumplimiento de Service Level Agreements (SLA), vulnerabilidades críticas de seguridad explotadas (fugas de datos, secuestro de información por ransomware), y una erosión incalculable de la confianza del usuario final.")
    
    add_p("Frente a esta realidad ineludible, el Aseguramiento de la Calidad del Software (Software Quality Assurance - SQA) no puede limitarse a la ejecución de validaciones empíricas desestructuradas; exige la adopción de marcos metodológicos rigurosos, fundamentados en estándares internacionales de la industria, y respaldados por plataformas tecnológicas capaces de centralizar y gobernar el volumen masivo de datos generados en el proceso. En particular, el Ciclo de Vida de las Pruebas de Software (Software Testing Life Cycle - STLC) requiere una trazabilidad de extremo a extremo que conecte indefectiblemente los requerimientos de negocio con los escenarios de prueba técnicos, los resultados empíricos de ejecución y los defectos encontrados, asegurando que cada línea de código desplegada esté respaldada por una verificación exhaustiva y auditable.")
    
    add_p("En este contexto de exigencia máxima, surge QAMS (Quality Assurance Management System). QAMS se concibe y diseña como una plataforma integral, moderna, escalable y robusta, orientada a gobernar de manera absoluta todas las fases del proceso de pruebas bajo los lineamientos del estándar internacional ISTQB CTFL v4.0 (International Software Testing Qualifications Board) y la normativa ISO/IEC/IEEE 29119. A diferencia de las soluciones fragmentadas o arcaicas que saturan el mercado, QAMS es una solución disruptiva que abraza el paradigma del Desarrollo Fullstack moderno, implementando un diseño de Monolito Modular respaldado por los principios de Clean Architecture y SOLID. Esta arquitectura de vanguardia aprovecha el máximo potencial del ecosistema .NET 9 con C# 13 en su capa de backend para garantizar un rendimiento transaccional seguro y concurrente, mientras que su frontend en Angular 19, potenciado por la reactividad atómica de Angular Signals y Standalone Components, ofrece una experiencia de usuario (UX) asíncrona, de ultra-baja latencia y visualmente superior gracias al uso de metodologías de diseño Glassmorphism y Tailwind CSS.")

    add_p("El presente documento académico de tesis/monografía expone de forma detallada y rigurosa la fundamentación teórica, el diseño arquitectónico de software, la ingeniería de requisitos funcionales y no funcionales, la implementación técnica a nivel de código fuente, el diseño del modelo relacional en base de datos PostgreSQL, la mitigación de brechas de seguridad según el estándar OWASP Top 10, y el estudio de viabilidad económica (Benchmark multicriterio y TCO) de la plataforma QAMS. Se demuestra científicamente y técnicamente cómo el uso del stack tecnológico .NET 9 / Angular 19, bajo un enfoque de monolito modular contenedorizado con Docker, supera ampliamente a las herramientas comerciales privativas tradicionales, posicionando a QAMS como la mejor alternativa para equipos de desarrollo y organizaciones de aseguramiento de calidad (QA).")

    add_h2("1.2 Antecedentes")
    add_p("El desarrollo de herramientas para la gestión del ciclo de vida del software ha estado intrínsecamente ligado a la evolución de las metodologías de desarrollo. Comprender los antecedentes del objeto de estudio resulta vital para justificar las decisiones de diseño adoptadas en la arquitectura de QAMS.")

    add_h3("1.2.1 Antecedentes del objeto de estudio")
    add_p("Históricamente, la gestión de la calidad del software y el testing comenzaron como actividades completamente artesanales en las décadas de 1970 y 1980, donde las validaciones se realizaban mediante scripts manuales o inspección visual de salidas en terminales, sin una traza documental auditable. Con el advenimiento de la ingeniería de software como disciplina formal, surgió la necesidad de estandarización documental. En 1998, la publicación del estándar IEEE 829 para la Documentación de Pruebas de Software marcó un hito, introduciendo conceptos como el Plan de Pruebas, Casos de Prueba, Procedimientos y Reportes de Anomalías. Este marco documental impulsó la creación de las primeras herramientas Application Lifecycle Management (ALM) de clase empresarial (como HP Quality Center, hoy OpenText ALM), diseñadas primariamente para los ciclos de desarrollo tradicionales o en cascada (Waterfall).")
    
    add_p("Durante las décadas de 2000 y 2010, la irrupción de las metodologías ágiles (Scrum, Kanban, Extreme Programming) transformó el panorama, exigiendo ciclos de entrega continuos (CI/CD) y validaciones ultrarrápidas. Las herramientas monolíticas heredadas resultaron ser excesivamente burocráticas, pesadas y costosas, dando paso al desarrollo de plataformas integradas a gestores de incidencias (como los plugins Zephyr Scale o Xray para Jira). Sin embargo, esta dependencia hacia terceros generó un nuevo problema: la pérdida de soberanía de los datos, la fragmentación de la gobernanza, una escalada insostenible en los costos de licenciamiento (SaaS) y arquitecturas fuertemente acopladas. Actualmente, en numerosas organizaciones tanto a nivel local como internacional (incluyendo startups y entidades estatales), el aseguramiento de calidad aún se gestiona a través de una amalgama ineficiente de hojas de cálculo de Microsoft Excel (para casos de prueba), correos electrónicos (para aprobaciones) y herramientas open-source descontinuadas funcionalmente como TestLink. Esta fragmentación metodológica rompe por completo la Matriz de Trazabilidad de Requisitos (RTM), imposibilitando saber si un requerimiento normativo crítico está cubierto por casos de prueba válidos, e incrementando de forma dramática el riesgo sistémico de que defectos mayores escapen a la fase de producción.")
    
    add_p("Es en esta encrucijada histórica y tecnológica que se fundamenta el proyecto QAMS: una necesidad imperiosa de retornar a los fundamentos de la calidad (certificación ISTQB), apoyados por una arquitectura de software propia, moderna, de código altamente mantenible, con reactividad en tiempo real y gobernanza absoluta de datos, pero accesible financieramente mediante un modelo self-hosted (despliegue local o VPS) libre del yugo de las suscripciones por usuario.")

    add_h3("1.2.2 Referencias técnicas de otros trabajos e Investigaciones Relacionadas")
    add_p("Para cimentar el rigor científico y el estado del arte de la presente monografía, se llevó a cabo un análisis bibliográfico y una revisión de literatura técnica exhaustiva, identificando trabajos académicos e industriales precedentes que abordan la gestión de calidad, arquitecturas de software para QA y la automatización del ciclo STLC. A continuación, se detallan tres referencias técnicas principales que han servido como punto de partida y contraste comparativo para la investigación:")

    add_bullet("1. Título: \"Desarrollo de un sistema web integral para la gestión, trazabilidad y ejecución automatizada de pruebas de software en entornos ágiles DevOps\".")
    add_p("   - Autor: Sánchez, Diego Fernando (2023). Tesis de Máster en Ingeniería de Software, Universidad Politécnica de Valencia.")
    add_p("   - Objetivo General: Implementar una plataforma de software orientada a microservicios en la nube (AWS) que permita centralizar los resultados de la ejecución de scripts automatizados de pruebas E2E (Selenium, Cypress) en pipelines de integración continua.")
    add_p("   - Resumen del Proyecto: El autor desarrolló una solución web donde el núcleo transaccional operaba sobre 12 microservicios independientes (escritos en Node.js, Go y Python) comunicados a través de buses de mensajería asíncrona (RabbitMQ) y un frontend en React. La plataforma lograba absorber grandes volúmenes de reportes XML generados por robots de automatización, agrupándolos en dashboards para los ingenieros de control de calidad.")
    add_p("   - Diferencia y Superación del Enfoque por QAMS: El trabajo de Sánchez presenta una alta complejidad arquitectónica y de infraestructura. El uso de microservicios para un gestor de pruebas (que es fundamentalmente una aplicación de gestión de estado relacional y trazabilidad documental altamente conectada) introdujo problemas severos de consistencia transaccional (eventual consistency), latencias de red internas elevadas, y un sobrecosto astronómico en infraestructura de nube (requiriendo clústeres Kubernetes para su operación básica). QAMS refuta este enfoque adoptando el paradigma del **Monolito Modular con Clean Architecture**. QAMS unifica los dominios (Requerimientos, Casos de Prueba, Ejecuciones, Defectos) en una única base de datos relacional robusta (PostgreSQL) y una API central (.NET 9), garantizando consistencia transaccional absoluta (ACID), latencia cero intra-proceso y la capacidad de desplegar todo el ecosistema en un modesto servidor VPS de $30 dólares mensuales usando un solo archivo Docker Compose. Además, QAMS es superior metodológicamente al integrar el diseño BDD (Gherkin) y métricas exclusivas del estándar ISTQB (Quality Gates), aspectos que el sistema de microservicios ignoró por centrarse puramente en los artefactos de DevOps.")

    add_bullet("2. Título: \"Plataforma de Gobernanza y Quality Assurance fundamentada en el cruce de metodologías tradicionales (Waterfall) y marcos ágiles\".")
    add_p("   - Autores: Gómez, Ricardo y Pérez, Laura (2022). Trabajo de Grado, Facultad de Informática, Universidad Autónoma del Estado de México.")
    add_p("   - Objetivo General: Estandarizar el ciclo de vida de los defectos de software y los planes de prueba mediante un sistema de gestión centralizado que permita a empresas gubernamentales certificar software.")
    add_p("   - Resumen del Proyecto: Se diseñó e implementó un sistema web tradicional monolítico utilizando el stack tecnológico LAMP (Linux, Apache, MySQL, PHP 7). El sistema logró informatizar la creación de planes de prueba y asociar defectos a testers específicos mediante flujos de estado cerrados, operando mediante la renderización de páginas del lado del servidor (Server-Side Rendering).")
    add_p("   - Diferencia y Superación del Enfoque por QAMS: Aunque funcional, el enfoque tecnológico de Gómez y Pérez (PHP + Renderizado del lado de servidor) es obsoleto para los estándares actuales de usabilidad, rendimiento y mantenibilidad. Cada interacción del tester requería la recarga completa de la página, generando una experiencia de usuario lenta y frustrante durante las exhaustivas sesiones de prueba. QAMS supera abismalmente este enfoque aplicando el **Desarrollo Fullstack SPA (Single Page Application)** moderno: utiliza Angular 19 en el frontend como un cliente inteligente y reactivo, donde el uso del motor de Reactividad Fina (Angular Signals) permite un \"Fast Runner\" en tiempo real, registrando resultados de pruebas en milisegundos sin recargar el navegador. En el backend, el uso de .NET 9 proporciona un manejo asíncrono no bloqueante nativo y tipos estáticos estrictos, reduciendo a cero los errores de runtime comunes en lenguajes dinámicos como PHP, mientras la seguridad se ve robustecida con interceptores de cifrado AES-256 mitigando todas las vulnerabilidades del OWASP Top 10 que suelen afectar a los sistemas LAMP convencionales.")

    add_bullet("3. Título: \"Implementación de herramientas Open Source (Software Libre) para el aseguramiento y control de calidad en Pequeñas y Medianas Empresas (PYMES) de TI\".")
    add_p("   - Autor: Martínez, Ana (2024). Artículo de Investigación Industrial, Revista Iberoamericana de Ingeniería de Software.")
    add_p("   - Objetivo General: Reducir drásticamente los costos operativos y de licenciamiento SaaS asociados a herramientas de QA en empresas de desarrollo incipientes mediante la adopción de stacks de código abierto.")
    add_p("   - Resumen del Proyecto: El estudio evaluó la viabilidad de utilizar TestLink (para la gestión de casos de prueba) integrado vía APIs y webhooks con MantisBT o Bugzilla (para la gestión de defectos). La conclusión demostró un ahorro financiero sustancial frente a herramientas como TestRail, pero destacó las dificultades crónicas de integración, el mantenimiento dual de dos servidores separados y la interfaz de usuario desfasada que generaba rechazo entre los desarrolladores jóvenes.")
    add_p("   - Diferencia y Superación del Enfoque por QAMS: QAMS toma el espíritu de reducción de TCO (Costo Total de Propiedad) planteado por Martínez, pero en lugar de forzar la integración frágil de dos herramientas antiguas de la década de los 2000, QAMS ofrece una solución unificada nativa. QAMS incluye su propio gestor de casos de prueba y un avanzado gestor de ciclo de vida de defectos (con tableros Kanban integrados) dentro de la misma interfaz y base de datos, garantizando una trazabilidad perfecta sin APIs inestables de intermediarios. QAMS es una solución moderna que enamora al usuario a través de una UI/UX refinada (Tailwind CSS, vistas de cristal, dashboards analíticos Ng2-Charts) y brinda características punteras como Pruebas Exploratorias basadas en Cartas (SBTM) y Revisiones Estáticas formales, todo en una única plataforma self-hosted, consolidando a QAMS no solo como una alternativa económica, sino tecnológica e intelectualmente superior.")

    add_h2("1.3 Descripción del objeto de estudio")
    add_p("El objeto central de estudio y abstracción computacional del presente proyecto es el Proceso Formal de Gestión, Diseño, Ejecución, Control y Gobernanza de las Pruebas de Software (STLC). QAMS aborda la complejidad de este ciclo orquestando una arquitectura de información jerárquica y relacional que modela fielmente las entidades del mundo real dictaminadas por el IEEE y el ISTQB.")
    
    add_p("La descripción detallada del objeto de estudio abarca los siguientes componentes y fases, los cuales han sido traducidos en el código fuente de QAMS como Entidades de Dominio (Domain Entities) protegidas por invariantes y reglas de negocio estrictas:")
    
    add_bullet("• Entorno de Organización y SUT (System Under Test): La base del ecosistema. Representa el software, sistema o servicio que será el objetivo empírico de las pruebas de calidad.")
    add_bullet("• Requerimientos Funcionales y No Funcionales: Especificaciones del negocio que el software debe cumplir. Constituyen el punto de partida (Génesis) para la Matriz de Trazabilidad de Requisitos (RTM).")
    add_bullet("• Planes de Prueba (Test Plans) y Suites (Test Suites): Instrumentos de gobernanza estratégica. Definen el alcance (Scope), los criterios de entrada y salida (Quality Gates), y las estrategias metodológicas. Las Suites actúan como agrupadores lógicos (e.g. \"Suite de Regresión de Módulo de Pagos\").")
    add_bullet("• Diseño de Casos de Prueba (Test Cases): Artefactos atómicos de verificación. QAMS soporta tanto el diseño clásico (Precondiciones, Pasos de acción, Resultado Esperado) como el enfoque de Diseño Dirigido por el Comportamiento (BDD - Behavior-Driven Development) mediante la estricta sintaxis Gherkin (Given-When-Then).")
    add_bullet("• Sesiones de Pruebas Estáticas e Inspecciones (Static Testing): Componente clave del syllabus ISTQB CTFL v4.0. Permite la validación de código, documentos y requerimientos mediante revisiones grupales sistemáticas (Walkthroughs o Inspecciones de Fagan) antes de compilar una sola línea de código, reduciendo la inyección de defectos tempranos.")
    add_bullet("• Sesiones de Pruebas Exploratorias (SBTM): Metodología de Session-Based Test Management. Permite a los testers experimentados aplicar heurísticas para explorar el sistema de forma no guionada, registrando notas y hallazgos bajo un límite de tiempo (Time-boxing) y con un objetivo claro (Charter).")
    add_bullet("• Ejecución del Ciclo de Vida (Fast Runner): El momento empírico de la verdad. La instancia en tiempo real donde un caso de prueba se contrasta contra el SUT, resultando en estados binarios absolutos: Aprobado (PASSED), Fallido (FAILED), Bloqueado (BLOCKED) o No Ejecutado (UNEXECUTED).")
    add_bullet("• Ciclo de Vida del Defecto (Defect Management): La consecuencia de un caso fallido. Un registro formal, rastreable y priorizado que transita por estados (Nuevo, Asignado, En Progreso, Resuelto, Verificado, Cerrado, Reabierto) gestionado mediante un tablero ágil integrado (Kanban).")
    
    add_p("La gobernanza sobre este objeto de estudio se asegura en QAMS mediante el patrón arquitectónico de Base de Datos de \"Soft-Delete\" y \"Audit Trail\". Absolutamente ningún registro es eliminado físicamente de la base de datos de PostgreSQL (preservando la integridad histórica y referencial para auditorías corporativas o peritajes forenses), registrándose siempre el usuario (CreatedBy, UpdatedBy) y las estampas de tiempo en formato UTC.")

    add_h2("1.4 Identificación del Problema")
    add_p("En el sector tecnológico nacional e internacional, los equipos de desarrollo de software (Devs) y aseguramiento de calidad (QA) enfrentan un entorno hostil caracterizado por presiones de tiempo, presupuestos reducidos y requerimientos volátiles. A través de la observación directa, entrevistas con profesionales de QA, encuestas en comunidades de ingeniería de software y el análisis bibliográfico, se ha identificado de manera indubitable que el ecosistema de herramientas de gestión de pruebas actuales presenta severas deficiencias sistémicas que atentan contra la calidad final del software.")
    
    add_p("El Árbol de Problemas (Diagrama de Ishikawa) elaborado para este proyecto identifica tres grandes dimensiones causales que alimentan el problema central:")
    
    add_bullet("1. Dimensión Económica y Comercial (Causas de Negocio): Las herramientas que lideran el cuadrante de Gartner o el mercado enterprise (Zephyr, TestRail, Jira Xray, HP ALM) aplican modelos de licenciamiento abusivos, con esquemas SaaS (Software as a Service) de pago mensual recurrente por cada usuario activo. Esto excluye financieramente a PYMES, startups tecnológicas locales y laboratorios universitarios, forzándolos a operar a ciegas o en entornos degradados (Excel).")
    add_bullet("2. Dimensión Metodológica y de Trazabilidad (Causas Estructurales): El uso de herramientas genéricas de ticketing (como Trello o el Jira básico sin plugins) para gestionar pruebas genera una ruptura catastrófica en la Matriz de Trazabilidad de Requisitos (RTM). Al estar desconectados los requerimientos de las pruebas, los equipos padecen el síndrome de la \"Falsa Cobertura\": creen haber probado todo, pero despliegan software donde funciones críticas carecen de aserciones. Esto derrumba KPIs vitales de ingeniería como el DRE (Defect Removal Efficiency), permitiendo fugas de defectos a los entornos de producción.")
    add_bullet("3. Dimensión Tecnológica y Arquitectónica (Causas de Ingeniería de Software): Las plataformas legadas sufren de enorme Deuda Técnica. Sus arquitecturas de monolitos monolíticos (Big Ball of Mud) acopladas, interfaces renderizadas en el servidor (SSR lento) y código heredado (PHP antiguo, Java Struts) generan tiempos de respuesta inaceptables (> 2 segundos por clic). Esto produce fricción operativa severa: un tester que debe ejecutar 200 casos de prueba diarios pierde horas semanales únicamente esperando recargas de páginas, mermando su productividad y su moral.")
    
    add_p("Este cóctel problemático deriva en un Efecto Central devastador: Software de calidad deficiente, entregado fuera de plazos, con métricas de calidad (Quality Gates) incalculables en tiempo real, equipos frustrados y costos de mantenimiento que se disparan en las fases productivas.")
    
    add_image_fig("figura1_ishikawa.png", "Figura 1: Diagrama de Causa y Efecto (Ishikawa) de la Problemática Estructural y Tecnológica en la Gestión Tradicional de QA")

    add_h2("1.5 Formulación del Problema")
    add_p("Tomando en cuenta la fenomenología descrita en la identificación del problema, la investigación se cristaliza en la siguiente pregunta científica y técnica rectora:")
    
    add_p("¿De qué manera el diseño, implementación y despliegue de una plataforma web empresarial integral —fundamentada estrictamente en los lineamientos técnicos del estándar internacional ISTQB CTFL v4.0 e ISO 29119, construida mediante el paradigma arquitectónico de Monolito Modular con Clean Architecture y principios SOLID (.NET 9 en el Backend y Angular 19 en el Frontend), orquestada en contenedores Docker y asegurada criptográficamente (OWASP Top 10)— permite optimizar radicalmente el ciclo de vida de las pruebas de software, resolviendo la fragmentación de herramientas, garantizando la trazabilidad bidireccional absoluta, reduciendo los tiempos operativos de registro y logrando una disminución sustancial del Costo Total de Propiedad (TCO) frente a las soluciones privativas de la industria actual?")

    add_h2("1.6 Objetivos")
    add_h3("1.6.1 Objetivo General")
    add_p("Diseñar la arquitectura, implementar a nivel de código fuente completo y validar operativamente una plataforma web empresarial fullstack de clase mundial denominada QAMS (Quality Assurance Management System), basada en una arquitectura de Monolito Modular con Clean Architecture, que centralice, automatice y gobierne el ciclo de vida completo de las pruebas de software bajo el estándar oficial ISTQB CTFL v4.0 e ISO/IEC/IEEE 29119, optimizando la trazabilidad RTM, la ejecución ergonómica de pruebas y el control holístico de defectos, todo ello con altos estándares de seguridad y en formato de código sostenible.")

    add_h3("1.6.2 Objetivos Específicos")
    add_p("La consecución del objetivo general se estructura lógica e iterativamente mediante el cumplimiento de los siguientes objetivos específicos fundacionales:")
    
    add_bullet("1. Ingeniería de Datos y Gobernanza: Diseñar y modelar la base de datos relacional (Entity-Relationship Diagram) garantizando la Normalización hasta la Tercera Forma Normal (3FN) en PostgreSQL 16. Implementar interceptores a nivel de Entity Framework Core 9 para garantizar políticas de Gobernanza de Datos (Soft-Delete universal, Audit Trail con timestamps UTC y trazabilidad de identidad del modificador).")
    add_bullet("2. Arquitectura de Backend .NET 9: Implementar el servidor API RESTful utilizando C# 13 y ASP.NET Core 9 aplicando rigurosamente los principios de Clean Architecture (desacoplamiento total en capas Domain, Application, Infrastructure y API) y principios SOLID (Single Responsibility, Dependency Inversion). Implementar seguridad profunda con mitigación proactiva del OWASP Top 10 mediante validaciones de Payload, autenticación JWT Bearer estricta, Control de Acceso Dinámico Basado en Roles (RBAC) y cifrado criptográfico simétrico AES-256 en tránsito.")
    add_bullet("3. Arquitectura de Frontend Angular 19: Desarrollar una Single Page Application (SPA) asíncrona, robusta y altamente reactiva en Angular 19. Desechar los módulos legados (NgModules) en favor de Standalone Components puros. Implementar la gestión de estado atómico y sin parpadeos visuales empleando la tecnología revolucionaria de Angular Signals. Construir una UI/UX envolvente utilizando Tailwind CSS y metodologías Glassmorphism para los módulos de Fast Runner, Matriz RTM, Dashboards analíticos (Ng2-Charts) y Tableros Kanban drag-and-drop.")
    add_bullet("4. Cumplimiento de Syllabus ISTQB: Traducir la teoría de aseguramiento de calidad en funciones de software concretas integrando los módulos avanzados dictados por ISTQB: Revisiones Estáticas Formales (Walkthroughs, Inspecciones), Pruebas Exploratorias apoyadas en Cartas (SBTM - Session-Based Test Management) y el cálculo automatizado de umbrales de certificación (Quality Gates).")
    add_bullet("5. Viabilidad Económica y Negocio: Efectuar un riguroso estudio estadístico de Benchmark multicriterio y un análisis financiero proyectado del Costo Total de Propiedad (TCO a 5 años) que contraste el costo operativo y la cobertura de QAMS frente a las cuatro herramientas privativas dominantes del mercado (TestRail, Zephyr, Xray, HP ALM).")
    add_bullet("6. Ingeniería de Despliegue y Orquestación DevOps: Desplegar el ecosistema completo (Servidor Web Nginx como Proxy Inverso, API Backend .NET 9, Base de Datos PostgreSQL 16 y Caché Redis 7) empleando tecnologías de Contenedorización con Docker y Docker Compose, garantizando aislamiento de procesos (sandboxing), facilidad de instalación (One-Click Deploy) y portabilidad infraestructural.")
    add_bullet("7. Pruebas y Validación (Testing the Testing Tool): Cerrar el ciclo validando el sistema QAMS aplicando las mismas prácticas que el software predica, mediante el diseño y ejecución de Pruebas Unitarias/Integración automatizadas (xUnit + WebApplicationFactory para la API de .NET), pruebas end-to-end de flujos críticos del frontend y pruebas de carga concurrente (k6) para asegurar los SLA de rendimiento (Tiempos P95 < 200ms).")

    add_h2("1.7 Justificaciones")
    add_p("El valor intrínseco del proyecto QAMS radica en su capacidad de transformar positivamente el panorama tecnológico, económico y formativo de las organizaciones de desarrollo de software. A continuación, se detalla el cuerpo argumentativo que justifica exhaustivamente la existencia de este proyecto.")

    add_h3("1.7.1 Justificación técnica, arquitectónica y de Ingeniería (Fullstack)")
    add_p("Técnicamente, el proyecto se erige como un \"Showcase\" (demostración maestra) de la superioridad de aplicar los principios modernos de Clean Architecture y la elección correcta de patrones arquitectónicos a nivel macro. En la industria actual existe una tendencia dogmática a implementar arquitecturas de microservicios para cualquier nuevo sistema, sin evaluar la penalidad de complejidad distribuida. QAMS justifica su diseño demostrando cómo el patrón de Monolito Modular (Modular Monolith) —donde todos los módulos residen en una misma base de código y base de datos relacional ACID, pero están estrictamente desacoplados a nivel lógico y de espacios de nombres (namespaces)— es inmensamente superior para dominios transaccionales densamente interconectados como lo es un STLC (donde un Defecto debe relacionarse inmediatamente con una Ejecución, un Caso, un Requisito, un SUT y un Analista).")
    add_p("Esta elección arquitectónica en .NET 9 anula por completo la latencia de red intra-servicio y los problemas de consistencia eventual característicos de los microservicios, logrando un sistema extremadamente eficiente (huella base de RAM menor a 250 MB en contenedores Alpine de Linux). Sumado a esto, el Frontend implementado con Angular Signals elimina el Change Detection ineficiente de las versiones anteriores (Zone.js), permitiendo que la interfaz del tester (Fast Runner) se actualice en microsegundos, optimizando el rendimiento humano a niveles inéditos en herramientas de QA comerciales que sufren de bloated-code.")
    add_p("A nivel de ciberseguridad, QAMS justifica su implementación técnica mitigando vectores de ataque que las herramientas de la competencia desestiman, inyectando cifrado AES-256 simétrico de lado del cliente y servidor para ofuscar los payloads HTTP interceptados, protegiendo así datos intelectuales altamente confidenciales (como la estructura de un software bancario en desarrollo) frente a vulnerabilidades del espectro OWASP.")

    add_h3("1.7.2 Justificación social y formativa-académica")
    add_p("A nivel social y organizacional, QAMS actúa como un agente democratizador de la tecnología de élite. Históricamente, solo las corporaciones Fortune 500 y megabancos podían permitirse plataformas de gestión ALM completas y seguras, obligando a las PYMES, startups locales, ONGs y laboratorios de investigación universitarios a conformarse con gestores mediocres o soluciones en Excel que destruyen la calidad del producto final. QAMS, al proveer una arquitectura self-hosted de grado empresarial, reduce la brecha tecnológica, otorgando herramientas de primer nivel a equipos reducidos y empoderando a la industria local de software para competir internacionalmente con productos libres de defectos.")
    add_p("En la dimensión formativa-académica, la interfaz y modelo de datos de QAMS fueron intencionalmente diseñados en torno a la semántica del ISTQB CTFL v4.0. Esto significa que los ingenieros junior y estudiantes que utilicen QAMS son guiados tácitamente (mediante la usabilidad y los flujos forzados de la herramienta) a adoptar las metodologías, terminologías y mejores prácticas del estándar internacional, sin requerir una capacitación extenuante previa. La herramienta se convierte así en un catalizador pedagógico para la profesionalización del rol del Analista de QA en la región.")

    add_h3("1.7.3 Justificación económica y financiera (TCO & ROI)")
    add_p("La justificación económica del sistema es contundente, fundamentada en matemáticas financieras de Costo Total de Propiedad (TCO). Las empresas que implementan herramientas privativas sufren la asfixia del gasto de licenciamiento SaaS (CAPEX convertido en un pesado OPEX recurrente).")
    add_p("Un cálculo conservador de TCO proyectado a 5 años para una célula ágil o departamento de TI compuesto por 15 profesionales (entre testers, leads y gestores de producto) revela lo siguiente:")
    add_bullet("• TestRail (Plan Enterprise Cloud): $74 por usuario/mes x 15 = $1,110/mes = $13,320/año. A 5 años el gasto asciende a $66,600 USD (sin incluir consultorías ni almacenamiento extra).")
    add_bullet("• QAMS (Auto-hospedado en la nube VPS AWS/DigitalOcean): Costo de licencia de la herramienta: $0 USD. Costo de un servidor robusto para contenedores Docker (e.g. 4 Cores, 8GB RAM): ~$40/mes = $480/año. A 5 años el costo de infraestructura totaliza apenas $2,400 USD.")
    add_p("El retorno financiero directo por la adopción de QAMS genera un Ahorro Operativo (ROI) de más de $64,200 USD en cinco años (reducción de costos de 96.4%). Este ahorro sustancial puede y debe ser redirigido estratégicamente por la empresa hacia la contratación de nuevo talento técnico, incremento salarial, investigación, desarrollo, y fortalecimiento del aseguramiento de calidad automatizado.")

    add_h2("1.8 Límites y Alcances")
    add_p("Definir con precisión matemática y metodológica las fronteras de un proyecto de ingeniería de software es imperativo para evitar el fenómeno de 'Scope Creep' (corrupción del alcance) y garantizar entregables tangibles, medibles y de alta calidad técnica.")

    add_h3("1.8.1 Límites (Fronteras y Out-of-Scope)")
    add_bullet("• Ejecución Automatizada Nativa: QAMS no es un motor de ejecución (runner) para ejecutar físicamente el código de pruebas automatizadas en los lenguajes de programación (como levantar el WebDriver de Selenium o Playwright y disparar clics en browsers). QAMS funciona como el Sistema de Gestión (ALM / Test Management), es decir, es el repositorio maestro que recibe, orquesta, almacena y procesa mediante analíticas los resultados de dichas ejecuciones, pero no invoca la compilación física de dichos scripts.")
    add_bullet("• Repositorios de Código Externos: En la actual fase inicial (v1.0), el sistema no provee integraciones nativas Out-of-the-Box de despliegue continuo (Webhooks bidireccionales con GitLab CI/CD, Jenkins o GitHub Actions). Toda integración automatizada requerirá consumo manual de las APIs RESTful expuestas por el backend de QAMS.")
    add_bullet("• Gestión Generalista de Mesa de Ayuda: Aunque QAMS incorpora un sofisticado módulo Kanban para la gestión del ciclo de vida del defecto o bug (Software Defect), el sistema NO está diseñado ni debe ser utilizado como un HelpDesk de atención a quejas o tickets de soporte técnico general de usuarios finales (ITSM).")

    add_h3("1.8.2 Alcances (Funcionalidades Fundamentales - In-Scope)")
    add_p("La versión 1.0 de la plataforma QAMS entregará de forma integral y validada bajo el marco ISTQB las siguientes macromódulos transaccionales y características arquitectónicas:")
    add_bullet("• Panel Central (Dashboard): Analítica de Quality Gates, Pass/Fail Rates, y Densidad de Defectos (DRE) integrando gráficos Ng2-Charts alimentados por Web APIs.")
    add_bullet("• Jerarquía de Gobernanza: Mantenimiento CRUD avanzado (Create, Read, Update, Soft-Delete) para catálogos, Sistemas Bajo Prueba (SUT), Proyectos y control de Requerimientos funcionales.")
    add_bullet("• Editor Dual de Casos de Prueba: Capacidad para diseñar casos de caja negra clásicos (por pasos instruccionales) y un editor nativo de BDD (Behavior-Driven Development) para escritura estricta en lenguaje Gherkin.")
    add_bullet("• Motor Fast Runner: Una interfaz ergonómica asíncrona (Signals) que permite a los QA registrar ejecuciones (Passed, Failed, Blocked) mediante atajos de teclado minimizando la fricción.")
    add_bullet("• Trazabilidad Absoluta (RTM): Matriz bidireccional que vincula Requirement ↔ Test Case ↔ Test Execution ↔ Defect.")
    add_bullet("• Pruebas Estáticas (Static Testing) e ISTQB Avanzado: Gestor de Sesiones de Walkthroughs y Pruebas Exploratorias Basadas en Sesiones (SBTM - Charters).")
    add_bullet("• Defect Tracking: Tablero interactivo (Drag and Drop Kanban) para el flujo de vida del defecto (Nuevo → Asignado → Resuelto → Validado → Cerrado).")
    add_bullet("• Infraestructura Dockerizada: Scripts de Docker-Compose con configuraciones óptimas de Nginx, variables de entorno seguras, y redes aisladas para despliegues instantáneos.")

    add_h2("1.9 Metodología de la investigación y Enfoque de Desarrollo")
    add_p("El rigor científico del proyecto queda asegurado por la selección y aplicación de un marco metodológico estructurado, que combina metodologías clásicas de investigación académica con las prácticas ágiles de la ingeniería de software moderna.")

    add_h3("1.9.1 Tipo de estudio")
    add_p("El presente trabajo de grado se circunscribe ontológica y epistémicamente dentro de la categoría de Investigación Tecnológica-Aplicada de enfoque Proyectivo. Es tecnológica porque persigue generar un nuevo artefacto o producto de software innovador como resultado final tangible. Es aplicada debido a que los conocimientos abstractos asimilados del análisis del ISTQB y las teorías arquitectónicas (SOLID, Clean Architecture) son instrumentados para resolver de manera empírica un problema estructural concreto en el mercado corporativo y los laboratorios de calidad de software.")

    add_h3("1.9.2 Métodos de Investigación Científica")
    add_bullet("• Método Analítico-Sintético: Se aplicó extensivamente durante la fase de análisis del dominio. El estándar ISTQB CTFL v4.0 (con cientos de páginas teóricas) fue sometido a una disección analítica minuciosa para extraer entidades atómicas computables, para posteriormente, mediante el proceso de síntesis, construir el Modelo Entidad-Relación y los Domain Driven Design (DDD) Aggregates del software QAMS.")
    add_bullet("• Método Experimental Computacional: Utilizado en la fase final (Capítulo 6), donde se validó el comportamiento del software en entornos controlados de laboratorio. Se simularon condiciones de estrés concurrente (K6 Load Testing con cientos de peticiones por segundo simulando múltiples QA's) y ataques cibernéticos emulados (OWASP vectors) para observar y garantizar matemáticamente que las métricas de rendimiento y seguridad definidas en los RNF (Requisitos No Funcionales) se cumplieran a cabalidad.")

    add_h3("1.9.3 Técnicas y Enfoque de Ingeniería (SDLC)")
    add_p("Para el diseño e implementación técnica, se fusionaron enfoques ágiles y robustos, garantizando la calidad del propio sistema:")
    add_bullet("• Ingeniería de Software Basada en Componentes: (Frontend) Se estructuró la aplicación en piezas reusables, atómicas e independientes mediante los Standalone Components de Angular, promoviendo el principio DRY (Don't Repeat Yourself).")
    add_bullet("• Diseño Guiado por el Dominio Estratégico (DDD Light): (Backend) El corazón del sistema (Capa Core) se escribió exento de cualquier dependencia a frameworks de base de datos o APIs externas, garantizando que el modelo lógico de negocio reine sobre la infraestructura.")
    add_bullet("• Técnicas de Recolección Documental e Ingeniería Inversa: Observación participativa y evaluación comparativa visual/funcional de herramientas líderes (Jira, Zephyr) para mapear flujos de trabajo fallidos y diseñar arquitecturas de experiencia de usuario (UX) curadas superiores para QAMS.")

    add_h2("1.10 Análisis preliminar")
    add_p("La fase del análisis investigativo preliminar destapó una desconexión crítica en la matriz del ecosistema de software contemporáneo. Mientras que los marcos teóricos sobre la Calidad del Software (como los estándares de la ISO/IEC 25010 y el ISTQB) han evolucionado y madurado significativamente introduciendo conceptos como la Gestión de Pruebas Exploratorias Basadas en Sesiones (SBTM), la revisión técnica formal y Quality Gates dinámicos; las herramientas prácticas de mercado no han logrado adaptarse a la misma velocidad.")
    add_p("El análisis del mercado evidenció un oligopolio donde escasas compañías dictan licencias exorbitantes, forzando a la adopción de plugins que canibalizan los ciclos de la CPU y saturan a los servidores de incidencias (como Jira) degradando su rendimiento principal. A la par, el auge descontrolado del hype de los microservicios ha provocado que muchos nuevos proyectos Open Source adopten arquitecturas distribuidas innecesariamente complejas, que luego fallan miserablemente debido a la incapacidad económica de orquestar la compleja topología requerida (Kubernetes, ELK stacks, Kafka) en proyectos de escala pequeña o mediana.")
    add_p("QAMS nace, por ende, validado por este análisis preliminar: el mercado mundial y local grita por la existencia de una plataforma que retorne a las raíces del rendimiento puro, una arquitectura limpia fuertemente unificada (Monolito), tipada, rápida, de cero costos de licenciamiento, e inviolablemente apegada a la normatividad ISTQB. La necesidad es clara y latente; la oportunidad de innovación es inmensa.")

    add_h2("1.11 Propuesta de solución")
    add_p("En respuesta directa a la fenomenología problemática identificada, se propone el desarrollo, ingeniería y liberación de la plataforma web QAMS (Quality Assurance Management System).")
    add_p("La propuesta de solución plantea un diseño Fullstack de vanguardia, donde la robustez del ecosistema empresarial de Microsoft .NET 9 se amalgama a la perfección con la velocidad reactiva del framework de Google Angular 19. El paradigma de Monolito Modular permitirá que toda la orquestación (desde la Matriz RTM, Casos de Prueba, Ejecuciones y Bug Tracking) comparta contexto transaccional en PostgreSQL 16 y alta disponibilidad de lectura de catálogos mediante caché distribuido en Redis 7.")
    add_p("Se propone que QAMS actúe no solo como un repositorio muerto de casos de prueba, sino como un ente vigilante que imponga flujos de gobernanza de datos mediante \"interceptores de seguridad y encriptación\", Quality Gates y flujos Kanban. La solución culminará empaquetada herméticamente en una configuración Docker Compose, permitiendo a cualquier equipo de la industria o del ámbito académico desplegar su propio entorno privado de pruebas en cuestión de minutos, con cero dependencias del sistema operativo anfitrión y asegurando la soberanía absoluta sobre su capital intelectual informático.")

    add_h2("1.12 Cronograma")
    add_p("El desarrollo de QAMS requirió un esfuerzo de ingeniería sistemático y disciplinado. El proyecto se estructuró a lo largo de un ciclo de desarrollo ágil de un semestre académico, dividido en cinco grandes fases que cubren el ciclo completo desde la ideación arquitectónica inicial hasta el empaquetado en contenedores y despliegue final en entornos pre-productivos.")
    
    headers_crono = ["Fase", "Descripción Detallada de Actividades del SDLC", "Duración (Semanas)"]
    rows_crono = [
        ["Fase 1: Análisis, Planificación y Arquitectura", "Disección literaria del estándar ISTQB CTFL v4.0. Benchmarking competitivo extenso. Levantamiento y especificación de Requerimientos Funcionales (Gherkin) y RNF (ISO 25010). Modelado de Arquitectura macro C4 (Contexto, Contenedores). Diseño de Diagrama Entidad-Relación y Normalización en 3FN.", "4 Semanas"],
        ["Fase 2: Ingeniería del Backend .NET 9 (Core)", "Configuración inicial de la solución .NET 9 LTS. Estructuración estricta de proyectos en Clean Architecture. Implementación de patrones (Repository, Unit of Work). Integración de Entity Framework Core 9 con migraciones PostgreSQL. Desarrollo de lógicas de seguridad (JWT, BCrypt, Filtros RBAC). Creación y prueba unitaria de Endpoints API RESTful.", "6 Semanas"],
        ["Fase 3: Desarrollo del Frontend SPA Angular 19", "Configuración del entorno Angular 19 estricto. Construcción del Sistema de Diseño (Design System) con Tailwind CSS y enfoques Glassmorphism. Implementación de Standalone Components y migración arquitectónica hacia Angular Signals para reactividad. Desarrollo del editor BDD Gherkin, Fast Runner, Matriz RTM interconectada y tableros drag-and-drop Kanban.", "6 Semanas"],
        ["Fase 4: Testing, Refactorización y OWASP", "Ciclo de pruebas intensivo (Dogfooding) utilizando la propia teoría QAMS para probar QAMS. Ejecución de pruebas de integración E2E con herramientas automatizadas. Auditoría de seguridad exhaustiva validando la matriz OWASP Top 10 (AES-256 interceptors). Resolución de Bugs de la Fase Beta. Optimización del tamaño de bundlers de Angular.", "3 Semanas"],
        ["Fase 5: Orquestación Docker y Generación Documental", "Construcción de archivos Dockerfile multi-stage para .NET y Nginx/Angular (Alpine base). Orquestación del ecosistema con Docker Compose (API, Web, DB, Redis, Mailhog). Redacción exhaustiva de la monografía académica (incluyendo todos los diagramas DFD, Modelos y arquitecturas C4) y desarrollo de scripts de auto-generación documental.", "3 Semanas"]
    ]
    add_custom_table(headers_crono, rows_crono, [1.5, 3.8, 0.9])

    doc.add_page_break()
"""

def inject():
    target_path = r"c:\diplomado\qams-web\scripts\generate_academic_monograph.py"
    with open(target_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Match the block starting from '# CAPÍTULO 1' up to 'doc.add_page_break()' right before '# CAPÍTULO 2'
    pattern = re.compile(
        r"(\s*# =========================================================================\s*"
        r"# CAPÍTULO 1: MARCO REFERENCIAL\s*"
        r"# =========================================================================\s*"
        r"add_h1\(\"Capítulo 1.- MARCO REFERENCIAL\"\).*?"
        r"doc\.add_page_break\(\)\s*)"
        r"(?=# =========================================================================\s*# CAPÍTULO 2:)", 
        re.DOTALL
    )

    if not pattern.search(content):
        print("Could not find Chapter 1 target block!")
        return
        
    new_content = pattern.sub(CHAPTER_1_CONTENT, content)
    
    with open(target_path, "w", encoding="utf-8") as f:
        f.write(new_content)
    
    print("Injection successful.")

if __name__ == "__main__":
    inject()
